---
- name: "verify foreman_content_view_version_cleanup_keep is set"
  assert:
    that:
      - foreman_content_view_version_cleanup_keep|int >= 0
    fail_msg: "foreman_content_view_version_cleanup_keep needs to be set to >= 0"

- name: "find all content views"
  theforeman.foreman.resource_info:
    server_url: "{{ foreman_server_url | default(omit) }}"
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    organization: "{{ foreman_organization }}"
    resource: content_views
    search: "{{ foreman_content_view_version_cleanup_search | default(omit) }}"
  register: all_cvs

- name: "delete unused composite content view versions"
  include_tasks: delete_cv_versions.yml
  vars:
    cv_name: "{{ ccv.name }}"
    cv_versions: "{{ (ccv.versions | rejectattr('environment_ids') | map(attribute='version') | map('float') | sort | map('string') | reverse | list)[foreman_content_view_version_cleanup_keep:] }}"
  loop: "{{ all_cvs.resources | selectattr('composite') | list }}"
  loop_control:
    label: "{{ ccv.label }}"
    loop_var: "ccv"
  when: (ccv.versions | rejectattr('environment_ids') | map(attribute='version') | reverse | list)[foreman_content_view_version_cleanup_keep:]

- name: "find and delete unused content view versions"
  include_tasks: find_and_delete_unused_cv_versions.yml
  loop: "{{ all_cvs.resources | rejectattr('composite') | list }}"
  loop_control:
    label: "{{ cv.label }}"
    loop_var: "cv"
  when: (cv.versions | rejectattr('environment_ids') | map(attribute='version') | reverse | list)[foreman_content_view_version_cleanup_keep:]
