namespace: "theforeman"
name: "foreman"
authors:
  - "Andrew Kofink <ajkofink@gmail.com>"
  - "Baptiste Agasse <baptiste.agasse@gmail.com>"
  - "Bernhard Hopfenmüller <hopfenmueller@atix.de>"
  - "Bernhard Suttner <sbernhard@users.noreply.github.com>"
  - "Chris Forkner <gen2fish@gmail.com>"
  - "Christoffer Reijer <christoffer.reijer@basalt.se>"
  - "Eric D. Helms <ericdhelms@gmail.com>"
  - "Evgeni Golov <evgeni@golov.de>"
  - "Greg Swift <gregswift@gmail.com>"
  - "Manuel Bonk <githubMB@bonkii.com>"
  - "Markus Bucher <bucher@atix.de>"
  - "Matthias Dellweg <dellweg@atix.de>"
  - "Philipp <philipp98.joos@gmail.com>"
  - "Quirin Pamp <Q.Pamp.2009@my.bristol.ac.uk>"
  - "Sean O'Keeffe <seanokeeffe797@gmail.com>"
version: "0.0.1"
license: "GPL-3.0-or-later"
tags:
  - foreman
  - katello
  - satellite
dependencies:
  ansible.version: ">= 2.3.0"
readme: "README.md"
repository: "https://github.com/theforeman/foreman-ansible-modules"
documentation: "https://theforeman.org/plugins/foreman-ansible-modules/"
issues: "https://github.com/theforeman/foreman-ansible-modules/issues"
