namespace: "theforeman"
name: "foreman"
description: Ansible Modules to manage Foreman and Katello installations
authors:
  - "@lessfoobar <59063885+lessfoobar@users.noreply.github.com>"
  - "Adam Růžička <aruzicka@redhat.com>"
  - "AlanCoding <arominge@redhat.com>"
  - "Andrew Kofink <ajkofink@gmail.com>"
  - "Anthony Green <green@moxielogic.com>"
  - "Anton <nesanton@gmail.com>"
  - "Baptiste Agasse <baptiste.agasse@gmail.com>"
  - "Bernhard Hopfenmüller <hopfenmueller@atix.de>"
  - "Bernhard Suttner <sbernhard@users.noreply.github.com>"
  - "Bryan Kearney <bkearney@redhat.com>"
  - "Chris Forkner <gen2fish@gmail.com>"
  - "Chris Hindman <chindman@chindman.remote.csb>"
  - "Chris Snell <chsnell@users.noreply.github.com>"
  - "Christoffer Reijer <ephracis@gmail.com>"
  - "Dave Thomas <11580510+dthomastx@users.noreply.github.com>"
  - "Deric Crago <deric.crago@gmail.com>"
  - "Eric D. Helms <ericdhelms@gmail.com>"
  - "Eric L <ericzolf@users.noreply.github.com>"
  - "Ethan <smithe2413@gmail.com>"
  - "Evgeni Golov <evgeni@golov.de>"
  - "Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl>"
  - "Felix Fontein <felix@fontein.de>"
  - "Gerald Vogt <gvde@users.noreply.github.com>"
  - "Greg Swift <gregswift@gmail.com>"
  - "Griffin Sullivan <gsulliva@redhat.com>"
  - "Hideki Saito <saito@fgrep.org>"
  - "Ismael Puerto <ismaelpuerto@users.noreply.github.com>"
  - "Jameer Pathan <jpathan@redhat.com>"
  - "James Jeffers <jjeffers@redhat.com>"
  - "James Stuart <james@stuart.name>"
  - "Jeffrey van Pelt <jeff@vanpelt.one>"
  - "Jeremy Albinet <jalbinet@scaleway.com>"
  - "Jeremy Lenz <jlenz@redhat.com>"
  - "Jesper Reenberg <jesper.reenberg@gmail.com>"
  - "John Berninger <john.berninger@gmail.com>"
  - "Josh Swanson <jswanson@redhat.com>"
  - "Kenny Tordeurs <ktordeur@redhat.com>"
  - "Kirill Shirinkin <fodojyko@gmail.com>"
  - "Leos Stejskal <lstejska@redhat.com>"
  - "Lester Cheung <lcheung@threatmetrix.com>"
  - "Lester Claudio <claudiol@redhat.com>"
  - "Lucas Bickel <hairmare@rabe.ch>"
  - "Lukáš Zapletal <lzap+git@redhat.com>"
  - "Manisha Singhal <manisha1595@gmail.com>"
  - "Manuel Bonk <githubMB@bonkii.com>"
  - "Marcelo Moreira de Mello <tchello.mello@gmail.com>"
  - "Marek Czernek <mczernek@redhat.com>"
  - "Mark Hlawatschek <hlawatschek@atix.de>"
  - "Markus Bucher <bucher@atix.de>"
  - "Martin Schlossarek <martin.schlossarek@gmail.com>"
  - "Matthias Dellweg <2500@gmx.de>"
  - "Miikka Joutsenvirta <miikka.joutsenvirta@dna.fi>"
  - "Nikhil Jain <jainnikhil30@gmail.com>"
  - "Olivier <oliverf1ca@yahoo.com>"
  - "Ondrej Prazak <oprazak@redhat.com>"
  - "Ondřej Ezr <oezr@redhat.com>"
  - "Ondřej Gajdušek <ogajduse@redhat.com>"
  - "Patrick C. F. Ernzer <pcfe@pcfe.net>"
  - "Patrick Creech <pcreech@redhat.com>"
  - "Paul Armstrong <parmstro@redhat.com>"
  - "Paul Belanger <pabelanger@redhat.com>"
  - "Paul Gration <pmgration@gmail.com>"
  - "Peter Ondrejka <pondrejk@redhat.com>"
  - "Philipp <philipp98.joos@gmail.com>"
  - "Quirin Pamp <pamp@atix.de>"
  - "Richard Stempfl <richielatk@gmail.com>"
  - "Sam <samcalvert@me.com>"
  - "Samir Jha <sjha4@ncsu.edu>"
  - "Sean O'Keeffe <seanokeeffe797@gmail.com>"
  - "Sorin Sbarnea <sorin.sbarnea@gmail.com>"
  - "Steffen Frömer <knumskull@users.noreply.github.com>"
  - "Stoned Elipot <stoned.elipot@gmail.com>"
  - "TTherouanne <thomas@therouanne.com>"
  - "Thomas Mueller <thomas@chaschperli.ch>"
  - "William Bradford Clark <wclark@redhat.com>"
  - "Yifat Makias <ymakias@redhat.com>"
  - "achevalet <anthony.chevalet@gmail.com>"
  - "bob <57952350+TheRedGreek@users.noreply.github.com>"
  - "calvingsmith <4283930+calvingsmith@users.noreply.github.com>"
  - "divialth <65872926+divialth@users.noreply.github.com>"
  - "furhouse <furhouse@users.noreply.github.com>"
  - "gardar <gardar@users.noreply.github.com>"
  - "igramic <36156377+igramic@users.noreply.github.com>"
  - "jerrejkw <43955357+jerrejkw@users.noreply.github.com>"
  - "marco <marco.markgraf@transporeon.com>"
  - "metalcated <mike.gomon@gmail.com>"
  - "russianguppie <46544650+russianguppie@users.noreply.github.com>"
  - "willtome <willtome@gmail.com>"
version: "3.11.0-dev"
license:
  - "GPL-3.0-or-later"
tags:
  - foreman
  - katello
  - satellite
  - orcharhino
  - infrastructure
readme: "README.md"
homepage: "https://theforeman.org/"
repository: "https://github.com/theforeman/foreman-ansible-modules"
documentation: "https://theforeman.org/plugins/foreman-ansible-modules/"
issues: "https://github.com/theforeman/foreman-ansible-modules/issues"
