namespace: "theforeman"
name: "foreman"
description: Ansible Modules to manage Foreman and Katello installations
authors:
  - "AlanCoding <arominge@redhat.com>"
  - "Andrew Kofink <ajkofink@gmail.com>"
  - "Anthony Green <green@moxielogic.com>"
  - "Anton <nesanton@gmail.com>"
  - "Baptiste Agasse <baptiste.agasse@gmail.com>"
  - "Bernhard Hopfenmüller <hopfenmueller@atix.de>"
  - "Bernhard Suttner <sbernhard@users.noreply.github.com>"
  - "Bryan Kearney <bkearney@redhat.com>"
  - "Chris Forkner <gen2fish@gmail.com>"
  - "Chris Snell <chsnell@users.noreply.github.com>"
  - "Christoffer Reijer <ephracis@gmail.com>"
  - "Deric Crago <deric.crago@gmail.com>"
  - "Eric D. Helms <ericdhelms@gmail.com>"
  - "Ethan <smithe2413@gmail.com>"
  - "Evgeni Golov <evgeni@golov.de>"
  - "Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl>"
  - "Greg Swift <gregswift@gmail.com>"
  - "Ismael Puerto <ismaelpuerto@users.noreply.github.com>"
  - "Jameer Pathan <jpathan@redhat.com>"
  - "Jeremy Albinet <jalbinet@scaleway.com>"
  - "John Berninger <john.berninger@gmail.com>"
  - "Kirill Shirinkin <fodojyko@gmail.com>"
  - "Lester Claudio <claudiol@redhat.com>"
  - "Manisha Singhal <manisha1595@gmail.com>"
  - "Manuel Bonk <githubMB@bonkii.com>"
  - "Marek Czernek <mczernek@redhat.com>"
  - "Mark Hlawatschek <hlawatschek@atix.de>"
  - "Markus Bucher <bucher@atix.de>"
  - "Matthias Dellweg <2500@gmx.de>"
  - "Nikhil Jain <jainnikhil30@gmail.com>"
  - "Olivier <oliverf1ca@yahoo.com>"
  - "Patrick Creech <pcreech@redhat.com>"
  - "Paul Armstrong <parmstro@users.noreply.github.com>"
  - "Paul Gration <pmgration@gmail.com>"
  - "Philipp <philipp98.joos@gmail.com>"
  - "Quirin Pamp <Q.Pamp.2009@my.bristol.ac.uk>"
  - "Richard <richielatk@gmail.com>"
  - "Sam <samcalvert@me.com>"
  - "Sean O'Keeffe <seanokeeffe797@gmail.com>"
  - "TTherouanne <thomas@therouanne.com>"
  - "William Bradford Clark <wclark@redhat.com>"
  - "calvingsmith <4283930+calvingsmith@users.noreply.github.com>"
  - "furhouse <furhouse@users.noreply.github.com>"
  - "jerrejkw <43955357+jerrejkw@users.noreply.github.com>"
  - "metalcated <mike.gomon@gmail.com>"
  - "russianguppie <46544650+russianguppie@users.noreply.github.com>"
  - "willtome <willtome@gmail.com>"
version: "1.0.0"
license:
  - "GPL-3.0-or-later"
tags:
  - foreman
  - katello
  - satellite
  - orcharhino
readme: "README.md"
homepage: "https://theforeman.org/"
repository: "https://github.com/theforeman/foreman-ansible-modules"
documentation: "https://theforeman.org/plugins/foreman-ansible-modules/"
issues: "https://github.com/theforeman/foreman-ansible-modules/issues"
