---
- name: Download Subscription Manifest from Red Hat Customer Portal
  theforeman.foreman.redhat_manifest:
    uuid: "{{ item.uuid }}"
    username: "{{ item.rhsm_username }}"
    password: "{{ item.rhsm_password }}"
    path: "{{ item.path }}"
  with_items: "{{ foreman_manifest | selectattr('download', 'defined') | list | default([]) }}"

- name: Upload Subscription Manifest to Foreman
  theforeman.foreman.subscription_manifest:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    organization: "{{ item.organization | default(foreman_organization) }}"
    manifest_path: "{{ item.path }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ foreman_manifest | default([]) }}"
