---
- name: Add content view filters
  theforeman.foreman.content_view_filter:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    organization: "{{ foreman_organization }}"
    name: "{{ content_view_filter.name }}"
    content_view: "{{ content_view.name }}"
    repositories: "{{ content_view_filter.repositories | default(omit) }}"
    filter_type: "{{ content_view_filter.filter_type }}"
    start_date: "{{ content_view_filter.start_date | default(omit) }}"
    end_date: "{{ content_view_filter.end_date | default(omit) }}"
    types: "{{ content_view_filter.types | default(omit) }}"
    date_type: "{{ content_view_filter.date_type | default(omit) }}"
    inclusion: "{{ content_view_filter.inclusion | default(omit) }}"
    errata_id: "{{ content_view_filter.errata_id | default(omit) }}"
    max_version: "{{ content_view_filter.max_version | default(omit) }}"
    min_version: "{{ content_view_filter.min_version | default(omit) }}"
    rule_name: "{{ content_view_filter.rule_name | default(omit) }}"
    version: "{{ content_view_filter.version | default(omit) }}"
    description: "{{ content_view_filter.description | default(omit) }}"
    architecture: "{{ content_view_filter.architecture | default(omit) }}"
    filter_state: "{{ content_view_filter.filter_state | default(omit) }}"
    original_packages: "{{ content_view_filter.original_packages | default(omit) }}"
    original_module_streams: "{{ content_view_filter.original_module_streams | default(omit) }}"
    rule_state: "{{ content_view_filter.rule_state | default(omit) }}"

- name: Add content view filter rules
  theforeman.foreman.content_view_filter_rule:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    organization: "{{ foreman_organization }}"
    content_view: "{{ content_view.name }}"
    content_view_filter: "{{ content_view_filter.name }}"
    context: "{{ content_view_filter_rule.context | default(omit) }}"
    date_type: "{{ content_view_filter_rule.date_type | default(omit) }}"
    end_date: "{{ content_view_filter_rule.end_date | default(omit) }}"
    errata_id: "{{ content_view_filter_rule.errata_id | default(omit) }}"
    max_version: "{{ content_view_filter_rule.max_version | default(omit) }}"
    min_version: "{{ content_view_filter_rule.min_version | default(omit) }}"
    name: "{{ content_view_filter_rule.name | default(omit) }}"
    start_date: "{{ content_view_filter_rule.start_date | default(omit) }}"
    stream: "{{ content_view_filter_rule.stream | default(omit) }}"
    types: "{{ content_view_filter_rule.types | default(omit) }}"
    version: "{{ content_view_filter_rule.version | default(omit) }}"
  loop: "{{ content_view_filter.rules | default([]) }}"
  loop_control:
    loop_var: content_view_filter_rule
