---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  # File paths are relative to collection root folder when collection is
  # installed but relative to meta/ when it is built, so we need symlink magic
  # See https://github.com/ansible/ansible-builder/issues/406#issuecomment-1195584188
  python: requirements.txt
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
