---
# tasks file for users
- name: set auth params
  set_fact:
    auth_params: &auth_params
      server_url: "{{ foreman_server_url }}"
      username: "{{ foreman_username }}"
      password: "{{ foreman_password }}"
      validate_certs: "{{ foreman_validate_certs }}"

# task for user creation
- name: Create user(s)
  theforeman.foreman.user:
    <<: *auth_params
    name: "{{ item.username }}"
    firstname: "{{ item.firstname | default(omit) }}"
    lastname: "{{ item.lastname | default(omit) }}"
    mail: " {{ item.email | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    admin: "{{ item.admin_rights | default(omit) }}"
    user_password: "{{ item.user_password }}"
    default_location: "{{ item.default_location | default(omit) }}"
    default_organization: "{{ item.default_organization | default(omit) }}"
    auth_source: "{{ item.auth_source | default(omit) }}"
    timezone: "{{ item.timezone | default(omit) }}"
    locale: "{{ item.user_locale | default(omit) }}"
    roles: "{{ item.roles | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    state: present
  loop: "{{ foreman_users }}"
  when: foreman_create_users |bool
  no_log: "{{ foreman_users_hide_log }}"

# task for usergroup creation
- name: Create usergroup(s)
  theforeman.foreman.usergroup:
    <<: *auth_params
    name: "{{ item.usergroupname }}"
    admin: "{{ item.admin_rights | default(omit) }}"
    roles: "{{ item.roles | default(omit) }}"
    users: "{{ item.users | default(omit) }}"
    state: present
  loop: "{{ foreman_usergroups }}"
  when: foreman_create_usergroups |bool

# tasks for ldap
- name: Connect Foreman with LDAP authentication(s)
  theforeman.foreman.auth_source_ldap:
    <<: *auth_params
    name: "{{ item.ldap_name }}"
    port: "{{ item.port | default(omit) }}"
    host: "{{ item.ldap_host }}"
    # on the fly value must be boolean
    onthefly_register: "{{ item.onthefly_register | default(omit) }}"
    account: "{{ item.ldap_account | default(omit) }}"
    account_password: "{{ item.ldap_password | default(omit) }}"
    base_dn: "{{ item.ldap_base_dn | default(omit) }} "
    groups_base: "{{ item.ldap_groups_base | default(omit) }}"
    server_type: "{{ item.ldap_server_type | default(omit) }}"
    attr_login: "{{ item.attr_login | default(omit) }}"
    attr_firstname: "{{ item.attr_firstname | default(omit) }}"
    attr_lastname: "{{ item.attr_lastname | default(omit) }}"
    attr_mail: "{{ item.attr_mail | default(omit) }}"
    attr_photo: "{{ item.attr_photo | default(omit) }}"
    state: present
  when: foreman_enable_ldap_auth |bool
  no_log: "{{ foreman_users_hide_log }}"
  loop: "{{ foreman_auth_sources }}"

# tasks for ext_usergroup
- name: Create external user group(s)
  theforeman.foreman.external_usergroup:
    <<: *auth_params
    # name of the external userg.
    name: "{{ item.external_usergroupname }}"
    auth_source_ldap: "{{ item.auth_source_ldap }}"
    # name of the group listed in Foreman
    usergroup: "{{ item.foreman_usergroup }}"
    state: present
  when: foreman_map_external_usergroups
  loop: "{{ foreman_linked_usergroups }}"
