---
- name: 'Create webhooks'  # noqa: args[module]
  theforeman.foreman.webhook:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    name: "{{ item.name }}"
    ca_path: "{{ item.ca_path | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    event: "{{ item.event }}"
    http_content_type: "{{ item.http_content_type | default(omit) }}"
    http_headers: "{{ item.http_headers | default(omit) }}"
    http_method: "{{ item.http_method | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    target_url: "{{ item.target_url | default(omit) }}"
    verify_ssl: "{{ item.verify_ssl | default(omit) }}"
    webhook_password: "{{ item.webhook_password | default(omit) }}"
    webhook_template: "{{ item.webhook_template | default(omit) }}"
    webhook_user: "{{ item.webhook_user | default(omit) }}"
  with_items: "{{ foreman_webhooks }}"
  no_log: "{{ item.webhook_password is defined }}"
