name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'theforeman/foreman-ansible-modules'
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Ansible
        run: pip install --upgrade ansible py antsibull-changelog
      - name: Build Ansible Collection
        run: make dist
      - name: Build Changelog
        run: antsibull-changelog generate --output release-changelog.txt --only-latest
      - name: Deploy Ansible Collection
        run: make publish GALAXY_API_KEY=${{ secrets.GALAXY_API_KEY }}
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} -F release-changelog.txt theforeman-foreman-*.tar.gz
